/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Beckn.Models
{
    /// <summary>
    /// Describes the cancellation terms of an item or an order. This can be referenced at an item or order level. Item-level cancellation terms can override the terms at the order level.
    /// </summary>
    [DataContract]
    public partial class CancellationTerm : IEquatable<CancellationTerm>
    {
        /// <summary>
        /// The state of fulfillment during which this term is applicable.
        /// </summary>
        /// <value>The state of fulfillment during which this term is applicable.</value>

        [DataMember(Name = "fulfillment_state")]
        public State FulfillmentState { get; set; }

        /// <summary>
        /// Indicates whether a reason is required to cancel the order
        /// </summary>
        /// <value>Indicates whether a reason is required to cancel the order</value>

        [DataMember(Name = "reason_required")]
        public bool? ReasonRequired { get; set; }

        /// <summary>
        /// Information related to the time of cancellation.
        /// </summary>
        /// <value>Information related to the time of cancellation.</value>

        [DataMember(Name = "cancel_by")]
        public Time CancelBy { get; set; }

        /// <summary>
        /// Gets or Sets CancellationFee
        /// </summary>

        [DataMember(Name = "cancellation_fee")]
        public Fee CancellationFee { get; set; }

        /// <summary>
        /// Gets or Sets Xinput
        /// </summary>

        [DataMember(Name = "xinput")]
        public XInput Xinput { get; set; }

        /// <summary>
        /// Gets or Sets ExternalRef
        /// </summary>

        [DataMember(Name = "external_ref")]
        public MediaFile ExternalRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancellationTerm {\n");
            sb.Append("  FulfillmentState: ").Append(FulfillmentState).Append("\n");
            sb.Append("  ReasonRequired: ").Append(ReasonRequired).Append("\n");
            sb.Append("  CancelBy: ").Append(CancelBy).Append("\n");
            sb.Append("  CancellationFee: ").Append(CancellationFee).Append("\n");
            sb.Append("  Xinput: ").Append(Xinput).Append("\n");
            sb.Append("  ExternalRef: ").Append(ExternalRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CancellationTerm)obj);
        }

        /// <summary>
        /// Returns true if CancellationTerm instances are equal
        /// </summary>
        /// <param name="other">Instance of CancellationTerm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancellationTerm other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FulfillmentState == other.FulfillmentState ||
                    FulfillmentState != null &&
                    FulfillmentState.Equals(other.FulfillmentState)
                ) &&
                (
                    ReasonRequired == other.ReasonRequired ||
                    ReasonRequired != null &&
                    ReasonRequired.Equals(other.ReasonRequired)
                ) &&
                (
                    CancelBy == other.CancelBy ||
                    CancelBy != null &&
                    CancelBy.Equals(other.CancelBy)
                ) &&
                (
                    CancellationFee == other.CancellationFee ||
                    CancellationFee != null &&
                    CancellationFee.Equals(other.CancellationFee)
                ) &&
                (
                    Xinput == other.Xinput ||
                    Xinput != null &&
                    Xinput.Equals(other.Xinput)
                ) &&
                (
                    ExternalRef == other.ExternalRef ||
                    ExternalRef != null &&
                    ExternalRef.Equals(other.ExternalRef)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FulfillmentState != null)
                    hashCode = hashCode * 59 + FulfillmentState.GetHashCode();
                if (ReasonRequired != null)
                    hashCode = hashCode * 59 + ReasonRequired.GetHashCode();
                if (CancelBy != null)
                    hashCode = hashCode * 59 + CancelBy.GetHashCode();
                if (CancellationFee != null)
                    hashCode = hashCode * 59 + CancellationFee.GetHashCode();
                if (Xinput != null)
                    hashCode = hashCode * 59 + Xinput.GetHashCode();
                if (ExternalRef != null)
                    hashCode = hashCode * 59 + ExternalRef.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(CancellationTerm left, CancellationTerm right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CancellationTerm left, CancellationTerm right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
