/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Beckn.Models
{ 
    /// <summary>
    /// Describes the products or services offered by a BPP. This is typically sent as the response to a search intent from a BAP. The payment terms, offers and terms of fulfillment supported by the BPP can also be included here. The BPP can show hierarchical nature of products/services in its catalog using the parent_category_id in categories. The BPP can also send a ttl (time to live) in the context which is the duration for which a BAP can cache the catalog and use the cached catalog.  &lt;br&gt;This has properties like bbp/descriptor,bbp/categories,bbp/fulfillments,bbp/payments,bbp/offers,bbp/providers and exp&lt;br&gt;This is used in the following situations.&lt;br&gt;&lt;ul&gt;&lt;li&gt;This is typically used in the discovery stage when the BPP sends the details of the products and services it offers as response to a search intent from the BAP. &lt;/li&gt;&lt;/ul&gt;
    /// </summary>
    [DataContract]
    public partial class Catalog : IEquatable<Catalog>
    { 
        /// <summary>
        /// Gets or Sets Descriptor
        /// </summary>

        [DataMember(Name="descriptor")]
        public Descriptor Descriptor { get; set; }

        /// <summary>
        /// Fulfillment modes offered at the BPP level. This is used when a BPP itself offers fulfillments on behalf of the providers it has onboarded.
        /// </summary>
        /// <value>Fulfillment modes offered at the BPP level. This is used when a BPP itself offers fulfillments on behalf of the providers it has onboarded.</value>

        [DataMember(Name="fulfillments")]
        public List<Fulfillment> Fulfillments { get; set; }

        /// <summary>
        /// Payment terms offered by the BPP for all transactions. This can be overriden at the provider level.
        /// </summary>
        /// <value>Payment terms offered by the BPP for all transactions. This can be overriden at the provider level.</value>

        [DataMember(Name="payments")]
        public List<Payment> Payments { get; set; }

        /// <summary>
        /// Offers at the BPP-level. This is common across all providers onboarded by the BPP.
        /// </summary>
        /// <value>Offers at the BPP-level. This is common across all providers onboarded by the BPP.</value>

        [DataMember(Name="offers")]
        public List<Offer> Offers { get; set; }

        /// <summary>
        /// Gets or Sets Providers
        /// </summary>

        [DataMember(Name="providers")]
        public List<Provider> Providers { get; set; }

        /// <summary>
        /// Timestamp after which catalog will expire
        /// </summary>
        /// <value>Timestamp after which catalog will expire</value>

        [DataMember(Name="exp")]
        public DateTime? Exp { get; set; }

        /// <summary>
        /// Duration in seconds after which this catalog will expire
        /// </summary>
        /// <value>Duration in seconds after which this catalog will expire</value>

        [DataMember(Name="ttl")]
        public string Ttl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Catalog {\n");
            sb.Append("  Descriptor: ").Append(Descriptor).Append("\n");
            sb.Append("  Fulfillments: ").Append(Fulfillments).Append("\n");
            sb.Append("  Payments: ").Append(Payments).Append("\n");
            sb.Append("  Offers: ").Append(Offers).Append("\n");
            sb.Append("  Providers: ").Append(Providers).Append("\n");
            sb.Append("  Exp: ").Append(Exp).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Catalog)obj);
        }

        /// <summary>
        /// Returns true if Catalog instances are equal
        /// </summary>
        /// <param name="other">Instance of Catalog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Catalog other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Descriptor == other.Descriptor ||
                    Descriptor != null &&
                    Descriptor.Equals(other.Descriptor)
                ) && 
                (
                    Fulfillments == other.Fulfillments ||
                    Fulfillments != null &&
                    Fulfillments.SequenceEqual(other.Fulfillments)
                ) && 
                (
                    Payments == other.Payments ||
                    Payments != null &&
                    Payments.SequenceEqual(other.Payments)
                ) && 
                (
                    Offers == other.Offers ||
                    Offers != null &&
                    Offers.SequenceEqual(other.Offers)
                ) && 
                (
                    Providers == other.Providers ||
                    Providers != null &&
                    Providers.SequenceEqual(other.Providers)
                ) && 
                (
                    Exp == other.Exp ||
                    Exp != null &&
                    Exp.Equals(other.Exp)
                ) && 
                (
                    Ttl == other.Ttl ||
                    Ttl != null &&
                    Ttl.Equals(other.Ttl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Descriptor != null)
                    hashCode = hashCode * 59 + Descriptor.GetHashCode();
                    if (Fulfillments != null)
                    hashCode = hashCode * 59 + Fulfillments.GetHashCode();
                    if (Payments != null)
                    hashCode = hashCode * 59 + Payments.GetHashCode();
                    if (Offers != null)
                    hashCode = hashCode * 59 + Offers.GetHashCode();
                    if (Providers != null)
                    hashCode = hashCode * 59 + Providers.GetHashCode();
                    if (Exp != null)
                    hashCode = hashCode * 59 + Exp.GetHashCode();
                    if (Ttl != null)
                    hashCode = hashCode * 59 + Ttl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Catalog left, Catalog right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Catalog left, Catalog right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
