/*
 * Beckn Protocol Core
 *
 * Beckn Core Transaction API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Beckn.Models
{
    /// <summary>
    /// Describes the return policy of an item or an order
    /// </summary>
    [DataContract]
    public partial class ReturnTerm : IEquatable<ReturnTerm>
    {
        /// <summary>
        /// The state of fulfillment during which this term IETF&#x27;&#x27;s applicable.
        /// </summary>
        /// <value>The state of fulfillment during which this term IETF&#x27;&#x27;s applicable.</value>

        [DataMember(Name = "fulfillment_state")]
        public FulfillmentState FulfillmentState { get; set; }

        /// <summary>
        /// Indicates whether the item is eligible for return
        /// </summary>
        /// <value>Indicates whether the item is eligible for return</value>

        [DataMember(Name = "return_eligible")]
        public bool? ReturnEligible { get; set; }

        /// <summary>
        /// Applicable only for buyer managed returns where the buyer has to return the item to the origin before a certain date-time, failing which they will not be eligible for refund.
        /// </summary>
        /// <value>Applicable only for buyer managed returns where the buyer has to return the item to the origin before a certain date-time, failing which they will not be eligible for refund.</value>

        [DataMember(Name = "return_time")]
        public Time ReturnTime { get; set; }

        /// <summary>
        /// Gets or Sets ReturnLocation
        /// </summary>

        [DataMember(Name = "return_location")]
        public Location ReturnLocation { get; set; }

        /// <summary>
        /// The entity that will perform the return
        /// </summary>
        /// <value>The entity that will perform the return</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum FulfillmentManagedByEnum
        {
            /// <summary>
            /// Enum CONSUMEREnum for CONSUMER
            /// </summary>
            [EnumMember(Value = "CONSUMER")]
            CONSUMEREnum = 0,
            /// <summary>
            /// Enum PROVIDEREnum for PROVIDER
            /// </summary>
            [EnumMember(Value = "PROVIDER")]
            PROVIDEREnum = 1
        }

        /// <summary>
        /// The entity that will perform the return
        /// </summary>
        /// <value>The entity that will perform the return</value>

        [DataMember(Name = "fulfillment_managed_by")]
        public FulfillmentManagedByEnum? FulfillmentManagedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReturnTerm {\n");
            sb.Append("  FulfillmentState: ").Append(FulfillmentState).Append("\n");
            sb.Append("  ReturnEligible: ").Append(ReturnEligible).Append("\n");
            sb.Append("  ReturnTime: ").Append(ReturnTime).Append("\n");
            sb.Append("  ReturnLocation: ").Append(ReturnLocation).Append("\n");
            sb.Append("  FulfillmentManagedBy: ").Append(FulfillmentManagedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ReturnTerm)obj);
        }

        /// <summary>
        /// Returns true if ReturnTerm instances are equal
        /// </summary>
        /// <param name="other">Instance of ReturnTerm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReturnTerm other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FulfillmentState == other.FulfillmentState ||
                    FulfillmentState != null &&
                    FulfillmentState.Equals(other.FulfillmentState)
                ) &&
                (
                    ReturnEligible == other.ReturnEligible ||
                    ReturnEligible != null &&
                    ReturnEligible.Equals(other.ReturnEligible)
                ) &&
                (
                    ReturnTime == other.ReturnTime ||
                    ReturnTime != null &&
                    ReturnTime.Equals(other.ReturnTime)
                ) &&
                (
                    ReturnLocation == other.ReturnLocation ||
                    ReturnLocation != null &&
                    ReturnLocation.Equals(other.ReturnLocation)
                ) &&
                (
                    FulfillmentManagedBy == other.FulfillmentManagedBy ||
                    FulfillmentManagedBy != null &&
                    FulfillmentManagedBy.Equals(other.FulfillmentManagedBy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FulfillmentState != null)
                    hashCode = hashCode * 59 + FulfillmentState.GetHashCode();
                if (ReturnEligible != null)
                    hashCode = hashCode * 59 + ReturnEligible.GetHashCode();
                if (ReturnTime != null)
                    hashCode = hashCode * 59 + ReturnTime.GetHashCode();
                if (ReturnLocation != null)
                    hashCode = hashCode * 59 + ReturnLocation.GetHashCode();
                if (FulfillmentManagedBy != null)
                    hashCode = hashCode * 59 + FulfillmentManagedBy.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ReturnTerm left, ReturnTerm right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ReturnTerm left, ReturnTerm right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
